apiVersion: v1
kind: ServiceAccount
metadata:
  name: qdrouterd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qdrouterd
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qdrouterd
subjects:
- kind: ServiceAccount
  name: qdrouterd
roleRef:
  kind: Role
  name: qdrouterd
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    application: router
  name: router
data:
  qdrouterd.json: |2+
    [
        [
            "router",
            {
                "id": "router-${HOSTNAME}",
                "mode": "interior"
            }
        ],
        [
            "listener",
            {
                "name": "interior-listener",
                "role": "inter-router",
                "port": 55672,
                "maxFrameSize": 16384,
                "maxSessionFrames": 640
            }
        ],
        [
            "listener",
            {
                "name": "amqp",
                "host": "",
                "port": 5672
            }
        ],
        [
            "address",
            {
                "prefix": "mc",
                "distribution": "multicast"
            }
        ]
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: router
  name: router
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      application: router
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: router
    spec:
      serviceAccountName: qdrouterd
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom: 
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: QDROUTERD_AUTO_MESH_DISCOVERY
          value: QUERY
        - name: QDROUTERD_CONF
          value: /etc/qdrouterd/qdrouterd.json
        - name: QDROUTERD_CONF_TYPE
          value: json
        - name: APPLICATION_NAME
          value: router
        volumeMounts:
        - mountPath: /etc/qdrouterd
          name: router-config
          readOnly: true

        image: quay.io/interconnectedcloud/qdrouterd:nightly
        imagePullPolicy: Always
        name: router
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - configMap:
          defaultMode: 420
          name: router
        name: router-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
